import type { DefaultSharedModuleContext, LangiumSharedServices } from 'langium';
import { EmptyFileSystem, createDefaultSharedModule, inject } from 'langium';

import { MermaidGeneratedSharedModule } from '../generated/module.js';
import { MermaidServiceRegistry } from './mermaidServiceRegistry.js';
import { createInfoServices } from '../index.js';

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMermaidServices(context: DefaultSharedModuleContext = EmptyFileSystem) {
  const shared: LangiumSharedServices = inject(
    createDefaultSharedModule(context),
    MermaidGeneratedSharedModule,
  );
  shared.ServiceRegistry = new MermaidServiceRegistry(shared);
  const { Info } = createInfoServices(context);
  shared.ServiceRegistry.register(Info);
  return { Info, shared };
}
